name: Manually deploy 
on: workflow_dispatch

jobs:
  build:
    name: Manually deploy
    runs-on: ubuntu-latest
    steps:
    - name: Delete and clone repo
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.WASE_DEPLOY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/qwict/
          rm -rf GoolWebGPU
          git clone https://github.com/Qwict/GoolWebGPU.git
          git status